# Generated by Django 6.0.4 on 2026-04-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('proprietaire', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
